// File generated by FlutterFire CLI.
// This is a placeholder - run 'flutterfire configure' to generate real config
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbUsuNxshUM3O9Mq7kRvTpIwPhhImoZaI',
    appId: '1:52381446839:web:6848ac37606f23b007d332',
    messagingSenderId: '52381446839',
    projectId: 'swipe-finance-ff1a8',
    authDomain: 'swipe-finance-ff1a8.firebaseapp.com',
    storageBucket: 'swipe-finance-ff1a8.firebasestorage.app',
    measurementId: 'G-PS1C8DK0LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-API-KEY-HERE',
    appId: 'YOUR-APP-ID-HERE',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'swipe-finance-ff1a8',
    storageBucket: 'swipe-finance-ff1a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-API-KEY-HERE',
    appId: 'YOUR-APP-ID-HERE',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'swipe-finance-ff1a8',
    storageBucket: 'swipe-finance-ff1a8.firebasestorage.app',
    iosBundleId: 'com.example.swipeSpend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-API-KEY-HERE',
    appId: 'YOUR-APP-ID-HERE',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'swipe-finance-ff1a8',
    storageBucket: 'swipe-finance-ff1a8.firebasestorage.app',
    iosBundleId: 'com.example.swipeSpend',
  );
}
